__default__:
    time: 00:30:00
    job-name:  1kBulls
    account: project_2002561
    ntasks: 1
    cpus-per-task: 1
    mem-per-cpu: 4000
    partition: small
    working-directory: /scratch/project_2001454/Run9/logs/
    nvme: 0

# Step1 - Preparations
################################################################################
Download_known_variants:
    job-name: Download_known_variants
    time: 0-05:00:00

Download_reference:
    job-name: Download_reference
    time: 0-05:00:00
    
Index_reference:
    job-name: Index_reference
    time: 04:00:00
    cpus-per-task: 20
    
Fai_Index_reference:
    time: 04:00:00
    job-name: GATK_index
    mem-per-cpu: 40000

# Step2 - Trimming
################################################################################
Trim_data:
    time: 04:00:00
    job-name: Trim_data
    cpus-per-task: 20

# Step3 - QC
################################################################################
fastqc_quality_control_raw_data:
    time: 04:00:00
    job-name: FastQC_raw_data
    cpus-per-task: 20
    
fastqc_quality_control_trimmed_data:
    time: 04:00:00
    job-name: FastQC_trimmed_data
    cpus-per-task: 20

# Step4 - Alignment
################################################################################
Align_data:
    time: 0-12:00:00
    job-name: Align_data
    cpus-per-task: 20
    
sort_and_index:
    time: 0-04:00:00
    job-name: Sort_and_Index
    
mark_duplictes:
    job-name: mark_duplicates
    time: 05:00:00
    mem-per-cpu: 100000

merge_bam_files:
    job-name: merge_bam_files
    time: 05:00:00
    mem-per-cpu: 100000
    
# Step5 - VariantCalling
################################################################################    
BaseRecalibration:
    time: 0-12:00:00
    job-name: Base_recalibration
    cpus-per-task: 20
    mem-per-cpu: 4000
    
PrintReads:
    time: 1-0:00:00
    job-name: Print_reads
    cpus-per-task: 20
    mem-per-cpu: 6000

BaseRecalibration_afterRecal:
    time: 0-12:00:00
    job-name: Base_recalibration_afterRecal
    cpus-per-task: 20
    mem-per-cpu: 4000

AnalyzeCovariates:
    time: 0-12:00:00
    job-name: Analyse_covariats
    cpus-per-task: 1
    mem-per-cpu: 80000

GATK_haplotypeCaller:
    time: 1-00:00:00
    job-name: GATK_haplotypeCaller
    cpus-per-task: 20
    mem-per-cpu: 4000

GATK_CallableLoci:
    time: 04:00:00
    job-name: GATK_callable_loci
    cpus-per-task: 1
    mem-per-cpu: 20000
    
GATK_DepthOfCoverage:
    time: 04:00:00
    job-name: GATK_DepthOfCoverage
    cpus-per-task: 1
    mem-per-cpu: 80000
    
GATK_combineGVCFs:
    time: 04:00:00
    job-name: GATK_combineGVCFs
    cpus-per-task: 1
    mem-per-cpu: 80000
