__default__:
    time: 00:30:00
    job-name:  1kBulls
    account: project_2002561
    ntasks: 1
    cpus-per-task: 1
    mem-per-cpu: 4000
    partition: small
    working-directory: /scratch/project_2001454/Run9/logs/
    nvme: 0

# Step1 - Preparations
################################################################################
Download_known_variants:
    time: 0-05:00:00

Download_reference:
    time: 0-05:00:00

# Step2 - Trimming
################################################################################
Trim_data:
    time: 04:00:00
    job-name: Trim_data
    cpus-per-task: 20

# Step3 - QC
################################################################################
fastqc_quality_control_raw_data:
    time: 04:00:00
    job-name: FastQC_raw_data
    cpus-per-task: 20

# Step4 - Alignment
################################################################################
Align_data:
    time: 04:00:00
    job-name: Align_data
    cpus-per-task: 20
sort_and_index:
