project-folder: "/scratch/project_2001454/Run9"                                               # Path to the project folder
reference: "/scratch/project_2001454/Run9/Reference/ARS-UCD1.2_Btau5.0.1Y.fa"
reference-fai: "/scratch/project_2001454/Run9/Reference/ARS-UCD1.2_Btau5.0.1Y.fa.fai"
reference-index: "/scratch/project_2001454/Run9/Reference/ARS-UCD1.2_Btau5.0.1Y.fa.amb"
samplesheet: "/scratch/project_2001454/Run9/sampleSheet.tsv"
samples: "/scratch/project_2001454/Run9/samples"
known-variants: "/scratch/project_2001454/Run9/Reference/ARS1.2PlusY_BQSR_v3.vcf"
local-scratch: $LOCAL_SCRATCH

urls:
    known-variants: "http://www.1000bullgenomes.com/doco/ARS1.2PlusY_BQSR_v3.vcf.gz"
    reference: "https://sites.ualberta.ca/~stothard/1000_bull_genomes/ARS-UCD1.2_Btau5.0.1Y.fa.gz"

params:
  trimmomatic:
    threads: 20
    illuminaclip: "/Trimmomatic/adapters/TruSeq3-PE-2.fa:2:30:3:1:true"
    leading: 20 
    trailing: 20  
    slidingwindow: "3:15"  
    avgqual: 20
    minlen: 35 
  fastqc:
    threads: 20
  bwa:
    rgpl: "ILLUMINA"
    threads: 20
  picard:
    distance: 2500 #100 for data generated on non-arrayed flowcells (ie from GAIIx, HiSeq1500/2000/2500), or 2500 for arrayed flowcell data (eg HiSeqX, HiSeq3000/4000, NovaSeq)
  gatk:
    threads: 20
singularity:
  1kbulls: "docker://fischuu/1kbulls:0.1"